import { SEARCH_KEYWORD_MIN_LENGTH } from "../utils/constants";

export const TEXT = {
  app: {
    name: 'StockFlow',
    nav: {
      products: 'Products',
    },
    theme: {
      toggleAria: 'Toggle theme',
      toLight: 'Switch to light mode',
      toDark: 'Switch to dark mode',
    },
    auth: {
      logout: 'Logout',
    },
  },
  common: {
    back: 'Back',
    cancel: 'Cancel',
    delete: 'Delete',
    deleting: 'Deleting...',
    saving: 'Saving...',
    saveFailed: 'Save failed',
    reset: 'Reset',
  },
  products: {
    pageTitle: 'Products',
    title: 'Products',
    add: '+ Add product',
    empty: 'No products yet. Create your first product.',
    searchPlaceholder: `Search by name or SKU (min ${SEARCH_KEYWORD_MIN_LENGTH} chars)`,
    searchHint: (remaining: number) =>
      `Type ${remaining} more character(s) to search`,
    loadFailed: 'Failed to load products',
    deleteSuccess: 'Product deleted successfully',
    deleteFailed: 'Delete failed',
    deleteDialog: {
      title: 'Delete Product',
      message: (name?: string) =>
        `Are you sure you want to delete "${name ?? ''}"? This cannot be undone.`,
      confirmText: 'Delete',
      cancelText: 'Cancel',
    },
    table: {
      pageTitle: "List",
      name: 'Name',
      sku: 'SKU',
      category: 'Category',
      quantity: 'Quantity',
      sellingPrice: 'Selling price',
      action: 'Action',
      view: 'View',
      edit: 'Edit',
      preview: 'Preview',
    },
    form: {
      createPageTitle: 'Create',
      editPageTitle: 'Edit',
      createTitle: 'Add product',
      editTitle: 'Edit product',
      createButton: 'Create product',
      editButton: 'Save changes',
      fields: {
        name: 'Name',
        category: 'Category',
        sku: 'SKU',
        active: 'Active',
        featured: 'Featured',
        description: 'Description',
        quantityOnHand: 'Quantity on hand',
        costPrice: 'Cost price',
        sellingPrice: 'Selling price',
        sizes: 'Sizes',
        image: 'Product image',
        lowStockThreshold: 'Low stock threshold',
      },
      categoryPlaceholder: 'Select category',
      uploadImage: 'Upload image',
      chooseImage: 'Choose image',
      imageRequired: 'Product image is required',
      createdSuccess: 'Product created successfully',
      updatedSuccess: 'Product updated successfully',
      loading: 'Loading product...',
    },
    detail: {
      pageTitle: "Details",
      title: 'Product details',
      imageLabel: 'Product image',
      noImage: 'No image',
      backToProducts: 'Back to products',
      loadFailed: 'Failed to load product',
      labels: {
        name: 'Name',
        sku: 'SKU',
        category: 'Category',
        quantityOnHand: 'Quantity on hand',
        costPrice: 'Cost price',
        sellingPrice: 'Selling price',
        lowStockThreshold: 'Low stock threshold',
        status: 'Status',
        sizes: 'Sizes',
        description: 'Description',
      },
      values: {
        na: '—',
        active: 'Active',
        inactive: 'Inactive',
        featuredSep: ' • Featured',
      },
    },
  },
  authPages: {
    pageTitle: 'USER',
    login: {
      pageTitle: 'Login',
      title: 'Welcome back',
      subtitle:
        'Sign in to view your inventory, update stock levels, and keep an eye on low-stock items.',
      submit: 'Sign in',
      submitting: 'Signing in...',
      failed: 'Login failed',
      newHere: 'New here?',
      createAccount: 'Create an account',
      fields: {
        email: 'Email',
        password: 'Password',
      },
      validation: {
        emailRequired: 'Email is required',
        emailValid: 'Email must be valid',
        passwordRequired: 'Password is required',
        passwordLen: 'Password must be greater than 5 characters',
      },
      marketing: {
        headline: 'Inventory that stays out of your way.',
        body:
          "A focused dashboard for tiny teams and solo founders. Track what you have, what's low, and what needs attention—without wrestling a full-blown ERP.",
        bullets: [
          'Instant view of total products and stock on hand',
          'One-click edits for quantities and prices',
          'Low-stock list so you never miss a refill',
        ],
        badge1: 'Built for internal demos & MVPs',
        badge2: 'No credit card · No setup wizard',
      },
    },
    signup: {
      pageTitle: 'Register',
      title: 'Create your StockFlow account',
      submit: 'Create account',
      submitting: 'Creating account...',
      failed: 'Signup failed',
      already: 'Already have an account?',
      signIn: 'Sign in',
      mismatch: 'Passwords do not match',
      fields: {
        organisationName: 'Organization name',
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm password',
      },
      validation: {
        orgRequired: 'Organization name is required',
        orgMin: 'Organization name must be at least 6 characters',
        orgMax: 'Organization name must be at most 15 characters',
        orgAlpha: 'Organization name must contain only alphabets',
        emailRequired: 'Email is required',
        emailValid: 'Email must be valid',
        passwordRequired: 'Password is required',
        passwordLen: 'Password must be greater than 5 characters',
        confirmRequired: 'Confirm password is required',
        confirmMatch: 'Passwords do not match',
      },
      marketing: {
        headline: 'Spin up a clean inventory in one afternoon.',
        body:
          'Start with a simple product list, track on-hand quantities, and see low stock at a glance. No complex setup or integrations.',
      },
    },
  },
} as const

